### ISSUE TITLE
wordpress xml file convert to markdown failed

### ISSUE THREAD

**Issue by hupantingxue** [dreikanter/wp2md#13]
The .xml file is exported by wordpress.

Traceback (most recent call last):
  File "/usr/bin/wp2md", line 9, in <module>
    load_entry_point('wp2md==0.8.1', 'console_scripts', 'wp2md')()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 299, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 2229, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.6/site-packages/pkg_resources.py", line 1948, in load
    entry = __import__(self.module_name, globals(),globals(), ['__name__'])
  File "/usr/lib/python2.6/site-packages/wp2md/wp2md.py", line 449
    meta = {field: meta.get(field, None) for field in fields}
                                           ^
SyntaxError: invalid syntax

**Comment by hupantingxue** [comment]
wp2md does not support Python 2.6. see also in:

https://github.com/dreikanter/wp2md/issues/6
