### ISSUE TITLE
Error on conversion

### ISSUE THREAD

**Issue by elvishp2006** [dreikanter/wp2md#14]
It is giving the following error in the conversion, if you want I can send you the exported file!

Dumping index to '/home/elvis/Downloads/export/index-1.md'
Traceback (most recent call last):
  File "/usr/local/bin/wp2md", line 9, in <module>
    load_entry_point('wp2md==0.8.1', 'console_scripts', 'wp2md')()
  File "/usr/local/lib/python2.7/dist-packages/wp2md/wp2md.py", line 657, in main
    parser.feed(text)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1640, in feed
    self._parser.Parse(data, 0)
  File "/usr/lib/python2.7/xml/etree/ElementTree.py", line 1549, in _end
    return self.target.end(self._fixname(tag))
  File "/usr/local/lib/python2.7/dist-packages/wp2md/wp2md.py", line 596, in end
    dump_channel(self.channel, self.items)
  File "/usr/local/lib/python2.7/dist-packages/wp2md/wp2md.py", line 457, in dump_channel
    meta['content'] = generate_toc(meta, items)
  File "/usr/local/lib/python2.7/dist-packages/wp2md/wp2md.py", line 382, in generate_toc
    content = meta.get('description', '') + '\n\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by davidak** [comment]
i had the same issue:

```
Traceback (most recent call last):
  File "/usr/local/bin/wp2md", line 9, in <module>
    load_entry_point('wp2md==0.8.1', 'console_scripts', 'wp2md')()
  File "/usr/local/lib/python3.5/site-packages/wp2md/wp2md.py", line 657, in main
    parser.feed(text)
  File "/usr/local/lib/python3.5/site-packages/wp2md/wp2md.py", line 596, in end
    dump_channel(self.channel, self.items)
  File "/usr/local/lib/python3.5/site-packages/wp2md/wp2md.py", line 457, in dump_channel
    meta['content'] = generate_toc(meta, items)
  File "/usr/local/lib/python3.5/site-packages/wp2md/wp2md.py", line 382, in generate_toc
    content = meta.get('description', '') + '\n\n'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
```

Python 3.5.1
Wordpress 4.4.2

**Comment by evandropastor** [comment]
Same issue here :/

**Comment by natasab** [comment]
same issue here python 2.7.12 on Ubuntu
