### ISSUE TITLE
Install fails due to mentioned encoding in `open('README.md', encoding="utf8").read()`

### ISSUE THREAD

**Issue by kmonsoor** [dreikanter/wp2md#17]
`pip install` fails from Github as well as `python setup.py install` fails after cloning from Github.

```python
kmonsoor: ~ $ pip install git+https://github.com/dreikanter/wp2md
Downloading/unpacking git+https://github.com/dreikanter/wp2md
  Cloning https://github.com/dreikanter/wp2md to /tmp/pip-vwLrD2-build
  Running setup.py (path:/tmp/pip-vwLrD2-build/setup.py) egg_info for package from git+https://github.c
om/dreikanter/wp2md
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-vwLrD2-build/setup.py", line 17, in <module>
        long_description=open('README.md', encoding="utf8").read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
 
  File "<string>", line 17, in <module>
 
  File "/tmp/pip-vwLrD2-build/setup.py", line 17, in <module>
 
    long_description=open('README.md', encoding="utf8").read(),
               
TypeError: 'encoding' is an invalid keyword argument for this function
 
----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip-vwLrD2-build
Storing debug log for failure in /home/kmonsoor/.pip/pip.log
kmonsoor: ~ $ pip -V
pip 1.5.4 from /usr/lib/python2.7/dist-packages (python 2.7)

```

**Comment by kmonsoor** [comment]
Tested on Windows8.1 and Linux64, Python 2.7.11, Python 2.7.6. Same issue.

**Comment by kmonsoor** [comment]
Proposed fix: Pull request: https://github.com/dreikanter/wp2md/pull/18

**Comment by davidak** [comment]
i don't had the problem with Python 3.5.1

**Comment by kmonsoor** [comment]
this issue has been fixed on https://github.com/dreikanter/wp2md/pull/18
